/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nimbus_nativestructs_CTripleSet */

#ifndef _Included_nimbus_nativestructs_CTripleSet
#define _Included_nimbus_nativestructs_CTripleSet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nimbus_nativestructs_CTripleSet
 * Method:    c_iterHasNext
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_nimbus_nativestructs_CTripleSet_c_1iterHasNext
  (JNIEnv *, jobject);

/*
 * Class:     nimbus_nativestructs_CTripleSet
 * Method:    c_iterNext
 * Signature: (Lnimbus/nativestructs/Triple;)V
 */
JNIEXPORT void JNICALL Java_nimbus_nativestructs_CTripleSet_c_1iterNext
  (JNIEnv *, jobject, jobject);

/*
 * Class:     nimbus_nativestructs_CTripleSet
 * Method:    c_iterRemove
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nimbus_nativestructs_CTripleSet_c_1iterRemove
  (JNIEnv *, jobject);

/*
 * Class:     nimbus_nativestructs_CTripleSet
 * Method:    c_setiter
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nimbus_nativestructs_CTripleSet_c_1setiter__
  (JNIEnv *, jobject);

/*
 * Class:     nimbus_nativestructs_CTripleSet
 * Method:    c_setiter
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_nimbus_nativestructs_CTripleSet_c_1setiter__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     nimbus_nativestructs_CTripleSet
 * Method:    c_setiter
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_nimbus_nativestructs_CTripleSet_c_1setiter__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     nimbus_nativestructs_CTripleSet
 * Method:    c_freeiter
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nimbus_nativestructs_CTripleSet_c_1freeiter
  (JNIEnv *, jobject);

/*
 * Class:     nimbus_nativestructs_CTripleSet
 * Method:    c_add
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_nimbus_nativestructs_CTripleSet_c_1add
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     nimbus_nativestructs_CTripleSet
 * Method:    c_clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nimbus_nativestructs_CTripleSet_c_1clear
  (JNIEnv *, jobject);

/*
 * Class:     nimbus_nativestructs_CTripleSet
 * Method:    c_print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nimbus_nativestructs_CTripleSet_c_1print
  (JNIEnv *, jobject);

/*
 * Class:     nimbus_nativestructs_CTripleSet
 * Method:    c_contains
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_nimbus_nativestructs_CTripleSet_c_1contains
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     nimbus_nativestructs_CTripleSet
 * Method:    c_isEmpty
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_nimbus_nativestructs_CTripleSet_c_1isEmpty
  (JNIEnv *, jobject);

/*
 * Class:     nimbus_nativestructs_CTripleSet
 * Method:    c_remove
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_nimbus_nativestructs_CTripleSet_c_1remove
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     nimbus_nativestructs_CTripleSet
 * Method:    c_size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_nimbus_nativestructs_CTripleSet_c_1size
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
