/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nimbus_nativestructs_CList */

#ifndef _Included_nimbus_nativestructs_CList
#define _Included_nimbus_nativestructs_CList
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nimbus_nativestructs_CList
 * Method:    c_add
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_nimbus_nativestructs_CList_c_1add__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     nimbus_nativestructs_CList
 * Method:    c_add
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_nimbus_nativestructs_CList_c_1add__ILjava_lang_String_2
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     nimbus_nativestructs_CList
 * Method:    c_clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nimbus_nativestructs_CList_c_1clear
  (JNIEnv *, jobject);

/*
 * Class:     nimbus_nativestructs_CList
 * Method:    c_contains
 * Signature: (Ljava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_nimbus_nativestructs_CList_c_1contains
  (JNIEnv *, jobject, jobject);

/*
 * Class:     nimbus_nativestructs_CList
 * Method:    c_get
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_nimbus_nativestructs_CList_c_1get
  (JNIEnv *, jobject, jint);

/*
 * Class:     nimbus_nativestructs_CList
 * Method:    c_indexOf
 * Signature: (Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_nimbus_nativestructs_CList_c_1indexOf
  (JNIEnv *, jobject, jobject);

/*
 * Class:     nimbus_nativestructs_CList
 * Method:    c_isEmpty
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_nimbus_nativestructs_CList_c_1isEmpty
  (JNIEnv *, jobject);

/*
 * Class:     nimbus_nativestructs_CList
 * Method:    c_lastIndexOf
 * Signature: (Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_nimbus_nativestructs_CList_c_1lastIndexOf
  (JNIEnv *, jobject, jobject);

/*
 * Class:     nimbus_nativestructs_CList
 * Method:    c_remove
 * Signature: (Ljava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_nimbus_nativestructs_CList_c_1remove__Ljava_lang_Object_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     nimbus_nativestructs_CList
 * Method:    c_remove
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_nimbus_nativestructs_CList_c_1remove__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     nimbus_nativestructs_CList
 * Method:    c_set
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_nimbus_nativestructs_CList_c_1set
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     nimbus_nativestructs_CList
 * Method:    c_size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_nimbus_nativestructs_CList_c_1size
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
