/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nimbus_nativestructs_CSet */

#ifndef _Included_nimbus_nativestructs_CSet
#define _Included_nimbus_nativestructs_CSet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nimbus_nativestructs_CSet
 * Method:    delete
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_nimbus_nativestructs_CSet_delete
  (JNIEnv *, jobject, jint);

/*
 * Class:     nimbus_nativestructs_CSet
 * Method:    newSet
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_nimbus_nativestructs_CSet_newSet
  (JNIEnv *, jobject);

/*
 * Class:     nimbus_nativestructs_CSet
 * Method:    c_add
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_nimbus_nativestructs_CSet_c_1add
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     nimbus_nativestructs_CSet
 * Method:    c_clear
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_nimbus_nativestructs_CSet_c_1clear
  (JNIEnv *, jobject, jint);

/*
 * Class:     nimbus_nativestructs_CSet
 * Method:    c_contains
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_nimbus_nativestructs_CSet_c_1contains
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     nimbus_nativestructs_CSet
 * Method:    c_isEmpty
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_nimbus_nativestructs_CSet_c_1isEmpty
  (JNIEnv *, jobject, jint);

/*
 * Class:     nimbus_nativestructs_CSet
 * Method:    c_remove
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_nimbus_nativestructs_CSet_c_1remove
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     nimbus_nativestructs_CSet
 * Method:    c_size
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_nimbus_nativestructs_CSet_c_1size
  (JNIEnv *, jobject, jint);

/*
 * Class:     nimbus_nativestructs_CSet
 * Method:    c_iterInit
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_nimbus_nativestructs_CSet_c_1iterInit
  (JNIEnv *, jobject, jint);

/*
 * Class:     nimbus_nativestructs_CSet
 * Method:    c_iterHasNext
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_nimbus_nativestructs_CSet_c_1iterHasNext
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     nimbus_nativestructs_CSet
 * Method:    c_iterNext
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_nimbus_nativestructs_CSet_c_1iterNext
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
